### ISSUE TITLE
Import From Source Control Fails

### ISSUE THREAD

**Issue by henricorselius** [chucktomasi/sn-learn-javascript#3]
When I run Import From Source Control from ServiceNow on this repo I get this error:

checksum.txt either is missing or contains an invalid checksum. Ensure your repository contains a valid, unmodified source image exported by an instance

**Comment by chucktomasi** [comment]
sorry for the confusion. The scripts provided for this lesson are meant as standalone. They were not intended to be imported in to ServiceNow (although that's not a bad idea for future projects that have more complex structures like tables.) These were meant to simply copy and paste from Git (or your local clone of the repo). Good luck.
